CONNECT cergy_le_parc/cergy_le_parc;
-- Creation des Tablespaces
CREATE TABLESPACE TS_UTILISATEURS 
DATAFILE 'ts_utilisateurs.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE 1G;

CREATE TABLESPACE TS_MATERIELS 
DATAFILE 'ts_materiels.dbf' SIZE 300M AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

CREATE TABLESPACE TS_GESTION 
DATAFILE 'ts_gestion.dbf' SIZE 400M AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

CREATE TABLESPACE TS_LOGS 
DATAFILE 'ts_logs.dbf' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 3G;

CREATE TABLESPACE TS_STOCK 
DATAFILE 'ts_stock.dbf' SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE 5G;


-- Deplacer les tables sur les tablespaces 
-- TS user
ALTER TABLE Utilisateurs MOVE TABLESPACE TS_UTILISATEURS;
-- Ts Materiels
ALTER TABLE Types_de_Materiels MOVE TABLESPACE TS_MATERIELS;
ALTER TABLE Matériels MOVE TABLESPACE TS_MATERIELS;
-- Ts gestion 
ALTER TABLE Attributions MOVE TABLESPACE TS_GESTION;
ALTER TABLE Tickets MOVE TABLESPACE TS_GESTION;
-- Ts logs
ALTER TABLE Event_Logs MOVE TABLESPACE TS_LOGS;
ALTER TABLE Notifications MOVE TABLESPACE TS_LOGS;
-- Ts stock
ALTER TABLE Stock MOVE TABLESPACE TS_STOCK;

